Fix Linter Error
After upgrading from golangci-lint v1.45.2 to v1.48.0 the below error is
failing the CI pipeline.

Error: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os,
and those implementations should be preferred in new code. See the specific function documentation for details.  (staticcheck)

Update all uses of package io/util to instead use package io in the code
base.